server:
  port : 8886

management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : ${EUREKA_URI:http://ec2-3-37-74-211.ap-northeast-2.compute.amazonaws.com:8761/eureka}

spring:
  zipkin:
    base-url: http://58.149.234.98:9411/
  datasource:
    url: jdbc:mysql://postbird.cbysjphhbaea.ap-northeast-2.rds.amazonaws.com:3306/postbird?serverTimezone=Asia/Seoul
    username: admin
    password: '{cipher}7f7872e62dd7e0a862661b267a5e1750515bc8ff34be934c4b71bdbee61e7b1d'
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      init-s-q-l: select 12
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000

security:
  oauth2:
    resource:
      userInfoUri: http://ec2-3-34-151-247.ap-northeast-2.compute.amazonaws.com:8887/api/v1/user/login

logging:
  file:
    path: /usr/local/pbletter/logs
  level:
    root: INFO
