eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : ${EUREKA_URI:http://58.149.234.98:8761/eureka}

security:
  oauth2:
    resource:
      userInfoUri: http://58.149.234.98:8887/api/v1/user/login
