server:
  port : 5005

logging:
  file:
    path: /usr/local/pbpost/logs
  level:
    root: INFO

spring:
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
